### ISSUE TITLE
L.MarkerClusterGroup is not an exported member.

### ISSUE THREAD

**Issue by github-mayur** [Asymmetrik/ngx-leaflet-markercluster#12]
i am not able to create marker cluster group because showing error

> frontend/node_modules/@types/leaflet/index"' has no exported member 'MarkerClusterGroup'.

have followed all steps and normal map is working properly

**Comment by reblace** [comment]
I assume it's a build error? Are you using Angular CLI?
Can you check the line number it's referencing and share the import statement?

Did you install the markercluter types?
```npm install @types/leaflet.markercluster```

**Comment by reblace** [comment]
Closing due to no response. It's likely the missing typings or a missing import.

**Comment by poznyakovskiy** [comment]
In case anybody else stumbles upon this: You need to add
```
import 'leaflet.markercluster';
```
in addition to importing `markerClusterGroup` from `leaflet`.
