### ISSUE TITLE
Ao.markerClusterGroup is not a function

### ISSUE THREAD

**Issue by Pluto100500** [Asymmetrik/ngx-leaflet-markercluster#14]
Hello, thanks for the good library.

I had a problem, after the project is build, an error occurs.
For the assembly, I use cli
![photo_2018-06-15_09-38-02](https://user-images.githubusercontent.com/6144770/41453820-d76ac550-707f-11e8-8342-a188865222c8.jpg)

**Comment by reblace** [comment]
If you could provide more context (e.g., code, package.json, etc.), that would help with trying to figure out what's going on. There's also a 504 error, which may mean that a dependency is not loading and is causing the issue.

**Comment by reblace** [comment]
Closing this as never heard back.
