### ISSUE TITLE
Images for clusters aren't displayed

### ISSUE THREAD

**Issue by templth** [Asymmetrik/ngx-leaflet-markercluster#17]
Hello,

I'm trying to use this plugin to display clusters of markers. It seems to work fine but I can't display images for clusters.

FYI I use this configuration in the angular cli config for `ngx-leaflet` for assets:

```
            "assets": [
              {
                "glob": "**/*",
                "input": "./node_modules/leaflet/dist/images",
                "output": "leaflet/"
              },
              "src/favicon.ico",
              "src/assets"
            ],
```

Thanks for your help!
Thierry

**Comment by reblace** [comment]
If you're trying to display custom images for markers, you also need to provide create custom markers with the image from the assets output directory as described here: https://github.com/Asymmetrik/ngx-leaflet#a-note-about-markers

```
let layer = marker([ 46.879966, -121.726909 ], {
   icon: icon({
      iconSize: [ 25, 41 ],
      iconAnchor: [ 13, 41 ],
      iconUrl: 'assets/marker-icon.png',
      shadowUrl: 'assets/marker-shadow.png'
   })
});
```

I'm not sure if you're saying that the default cluster circle isn't showing up, or if you're trying to override the cluster circle with an image and that's not showing up, or if you are just not able to get marker images to show up. The last one (and the others I'd assume) requires you do the above marker with custom image to make it work.

**Comment by templth** [comment]
Thanks for your answer!

In fact, markers are correctly displayed. It's only for marker clusters. I also see the number of markers in the cluster, as shown below:

![screenshot from 2018-12-31 08-44-15](https://user-images.githubusercontent.com/558344/50556364-5a5ca100-0cd8-11e9-8745-4c88f59ffb40.png)

Here is how I add markers:

```
<div class="my-map no-padding"
  leaflet 
  [leafletOptions]="options"
  [leafletMarkerCluster]="markers"
  [leafletMarkerClusterOptions]="markerClusterOptions"
  (leafletMapReady)="onMapReady($event)"
  (leafletMapMove)="onMapChange($event)"
  (leafletMapZoom)="onMapChange($event)">
</div>
```

and in the component class:

```
this.markers = pois.map(poi => {
  const poiMarker = marker(
    [ poi.location.lat, poi.location.lng ],
    {
      icon: icon({
        iconSize: [ 25, 41 ],
        iconAnchor: [ 13, 41 ],
        iconUrl: 'leaflet/marker-icon.png',
        shadowUrl: 'leaflet/marker-shadow.png'
      })
    }
  );
  poiMarker.bindPopup(poi.label);

  return poiMarker;
});
```

**Comment by reblace** [comment]
Similar to how you have to include the styles for leaflet, did you also import the styles for the leaflet.markercluster?

node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css

**Comment by templth** [comment]
I didn't... Adding this fixed the problem. Thanks very much!

**Comment by jr24jr** [comment]
**in the component you import the images**

import 'leaflet/dist/images/marker-shadow.png';
import 'leaflet/dist/images/marker-icon.png';

**if you plan to use another custom icon you can use this setting**

let greenicon = L.icon({
      iconUrl: 'assets/leaflet/img/marker-icon-green.png',
      shadowUrl: 'assets/leaflet/img/marker-shadow.png',
      iconSize:     [25, 41], 
      shadowSize:   [41, 41], 
      iconAnchor:   [25, 41], 
      shadowAnchor: [25, 41], 
      popupAnchor:  [-12, -33] 
});

**iconUrl:** and **shadowUrl:** is the path of the image
