### ISSUE TITLE
Peer dependencies Angular 10

### ISSUE THREAD

**Issue by chop-suey** [Asymmetrik/ngx-leaflet-markercluster#38]
I am using the plugin in a Angular 10 app.

In Angular 10 tslib@2 is used. Thus the peer dependency to tslib@1 cannot be fullfilled.
Another peer dependency declared by this lib is leaflet@2.

As far as i know the latest version of leaflet is 1.7 and there is no version 2.

**Comment by reblace** [comment]
Just pushed 5.0.1 to fix this. It was just a typo...
